OPS-2348 Create FPDS MissingSubtierCGAC output file
fedspendingtransparency/data-act-broker-backend pull request #2350
Opened 2022-08-24 13:58 UTC by jasvatos

**High level description:**
Output the FPDS `MissingSubtierCGAC` messages to a file to use for notifications.

**Technical details:**
This creates a file that is later parsed during the FPDS pipeline run to add a notification if a `MissingSubtierCGAC` error is encountered.

**Link to JIRA Ticket:**
[OPS-2348](https://federal-spending-transparency.atlassian.net/browse/OPS-2348)

The following are ALL required for the PR to be merged:
- [ ] Backend review completed
- [ ] Style Guide check completed

2022-08-24 14:22 UTC, alburde1 reviewed
My only thought here: is it possible to store these in an array and then write the array to the file at the end of the process instead? So we aren't opening and closing a file potentially thousands of times in a single run. Optionally, if you go that route and want to go a tiny bit deeper you can pre-parse it while writing, but that might be more work depending on how you intend to parse this file.

2022-08-24 15:47 UTC, alburde1 submitted a review, later dismissed

2022-08-24 15:58 UTC, boozallendanny submitted a review, later dismissed

2022-08-24 18:11 UTC, gpontejos approved these changes

2022-08-25 15:17 UTC, dpb-bah requested changes

2022-08-25 15:17 UTC, dpb-bah commented on dataactcore/scripts/pull_fpds_data.py
> +    if cgacErrors != {}:
Could just do `if cgacErrors:`
```
>>> a = {}
>>> if a:
...  print('y')
... 
>>> (blank)
```

2022-08-25 15:47 UTC, dpb-bah approved these changes

2022-08-26 19:28 UTC, BFOSTER72 approved these changes

2022-08-26 19:48 UTC, merged

2022-08-26 19:49 UTC, BFOSTER72 commented
Pull request successfully merged and closed